### PR TITLE
feat: add domain provider

### PR DESCRIPTION
**Pull request by rygilles**
This PR add a new `domain` provider

### CODE REVIEW

**Comment by j6s** [comment]
Oh, I like this a lot. I only had a quick look, but the code seems good.

I'll test this in my local setup and will report, if I find something

**Comment by rygilles** [comment]
Hi, any news on this ?
I'm using the fork for my project but I thing it could be usefull for everyone.

**Comment by j6s** [comment]
Oh hey, I absolutely forgot about this - I thought I had already merged it.

**Comment by j6s** [comment]
This will in the future be part of a 1.4.0 release - for now, the `main` and `latest` docker images will contain changes from this PR.

**Comment by rygilles** [comment]
Thanks ! :)

**Pull request merged**
